### PR TITLE
Configuration set filtering logic fixed

### LINKED ISSUE #39: Changing File Name Outside of Configuration Set Locks Out File Changes
On disk, a user has a folder named `Barr`.
In their configuration though, they type `Bar`.

This triggers `on_update_configuration`, which triggers a compilation.
`slicec` fails to resolve the path, since `Bar` doesn't exist on disk. It returns `(ast: [], files: [], diagnostics: [io_errors])`.
Unrelated to this issue, but we should report these diagnostics to the user (see #38).

More importantly, `slicec` gave us an empty file list. We store this in `CompilationState`.
Because of this, the language server _thinks_ that the configuration-set has no files in it.

And, to be efficient, whenever a file changes, we only trigger compilations for configuration-sets including this file.
So, even when the user fixes the name of the folder, we go to trigger compilations, see that the configuration-set has no files, and skip it.
Effectively locking this error into place forever.

### PR DESCRIPTION
**Pull request by ReeceHumphreys**
Fixes #39

### CODE REVIEW

File: server/src/diagnostic_ext.rs [hunk 1]
```diff
@@ -52,11 +45,17 @@ pub async fn compile_and_publish_diagnostics(
 ) {
     let mut configuration_sets = configuration_sets.lock().await;
 
+    client
+        .log_message(
+            MessageType::INFO,
+            "Publishing diagnostics for all configuration sets..",
```
Comment (InsertCreativityHere) [inline server/src/diagnostic_ext.rs:51]: An ellipsis usually has 3 periods in it.
```suggestion
            "Publishing diagnostics for all configuration sets...",
```

**Review by InsertCreativityHere — APPROVED** [review]
Looks good to me!
